export const METRO_DETROIT_COURSES: string[] = [
  'Prestwick Village Golf Club',
  'Cracklewood Golf Club',
  'Cherry Creek Golf Club',
  'Fieldstone Golf Club',
  'Pine Trace Golf Club',
  'Stonebridge Golf Club',
  'Twin Lakes Golf Club',
  'Hickory Hills Golf Club',
  'Copper Creek Golf Club',
  'Hawk Meadows Golf Club',
  'Partridge Creek Golf Club',
  'Gleneagles Golf Club',
  'The Links at Gateway',
  'Fox Hills Golf and Banquet Center',
  'Hillendale Country Club',
  'Salem Hills Golf Club',
  'Idyl Wyld Golf Course',
  'Tanglewood Golf Club',
  'Coyote Golf Club',
  'Heather Highlands Golf Club',
  'West Bloomfield Golf Club',
  'Shepherds Hollow Golf Club',
  'White Pines Golf Club',
  'Rackham Golf Course',
  'Rogell Golf Course',
]
